name: WORDSLY CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: git checkout
        uses: actions/checkout@v2
      - name: npm install
        run: npm ci
      - name: eslint
        run: npm run lint
      - name: jest
        run: npm run test -- --coverage
      - name: jest:coverage
        uses: codecov/codecov-action@v3
